URL_BASE = "https://towneshops.directedje.com/Galardi"
URL_LOGIN = URL_BASE+"/login.asp"
URL_PRODUCT_DETAIL = URL_BASE+"/product-details.asp?"
URL_PRODUCT_LISTING = URL_BASE+"/product-listing.asp?"
URL_HOME = URL_BASE + "/catalog.asp"